blank_issues_enabled: false
contact_links:
  - name: Immersive Adventure Homepage
    url: https://modrinth.com/modpack/immersive-adventure
    about: "Huge props to the FTB team for making these ISSUE_TEMPLATEs!"
